---
# runs through and configures interfaces on a given host
# the interfce command variable should be set with the correct
# parameters
#
# Right now you can set the following parameters
# access vlan
# switchport mode
# channel-group
# speed 40g
# mlag number
# description
# trunk native vlan
#
# If you want to add the configs you need to set action == add
# If you want to remove the configs you need to set the action == del
#
# So if you want to remove the access vlan make sure you have
# access_vlan set to a value and action set to del.  If the action is del
# then every command that is uncommented and has a value with be removed
# 
# To Run:
# ansible-playbook  config_int_commands.yaml
- hosts: all
  gather_facts: no
  connection: local
 
  vars:
     range: et1/1
     conf_action: add
     interface_cmds:
          # - name:  "{{ range }}"
           #  description: 'storage'
            # access_vlan: 153
            # native_vlan: 2202
           #  mode: trunk 
            # channel_group: 303
            # mlag_channel: 303
            # speed_40: Forced

           - name:  et1/1
             description: 'storage'
             channel_group: 1001
             speed_40: Forced 
           - name:  et2/1
             description: 'storage'
             channel_group: 1002            
             speed_40: Forced 
           - name:  et3/1
             description: 'storage'
             channel_group: 1003
             speed_40: Forced
           - name:  et4/1
             description: 'storage'
             channel_group: 1004
             speed_40: Forced
           - name:  et5/1
             description: 'storage'
             channel_group: 1005
             speed_40: Forced
           - name:  et6/1
             description: 'storage'
             channel_group: 1006
             speed_40: Forced
           - name:  et7/1
             description: 'storage'
             channel_group: 1007
             speed_40: Forced
           - name:  et8/1
             description: 'storage'
             channel_group: 1008
             speed_40: Forced
           - name:  et9/1
             description: 'storage'
             channel_group: 1009
             speed_40: Forced
           - name:  et10/1
             description: 'storage'
             channel_group: 1010
             speed_40: Forced
           - name:  et11/1
             description: 'storage'
             channel_group: 1011
             speed_40: Forced
           - name:  et12/1
             description: 'storage'
             channel_group: 1012
             speed_40: Forced  
           - name:  et13/1
             description: 'storage'
             channel_group: 1013
             speed_40: Forced
           - name:  et14/1
             description: 'storage'
             channel_group: 1014
             speed_40: Forced
           - name:  et15/1
             description: 'storage'
             channel_group: 1015
             speed_40: Forced
           - name:  et16/1
             description: 'storage'
             channel_group: 1016
             speed_40: Forced



             
  tasks:
    - name: run commands
      eos_config:
         provider: "{{ provider_user_cli }}"
         src: int_config.j2
         save: true
 



