---
# This playbook will push out the root user and ansible user
# configuration to each host
#
# We are using the provider_user connection dictionary because this 
# playbook actually configures the ansible user that will be used for
# the ssh key based connection later
#
# This playbook will most likely be run as part of the push_ansible_keys
# parent playbook
#
# To invoke invdivually:
#
# ansible-playbook deploy_root_user.yaml 
- hosts: all
  gather_facts: no
  connection: local

  tasks:
     - name: enable root user
       eos_config:
          lines: 
             - "aaa root secret passwordhere"
             - "username ansible privilege 15 secret passwordhere"
          provider: "{{ provider_user }} "
 
     - name: copy run start
       eos_command:
           commands: "write memory"
           provider: "{{ provider_user }}"
    
