---
- hosts: dev-cisco     
  gather_facts: no
  connection: local

  tasks:
     - name: "add vlan range"  
       nxos_config:
          lines:
             - "vlan {{ item.id }}"
          provider: "{{ provider_cisco }}"
          save: yes
       with_items: "{{  vlans_to_add }}"
       when: item.state ==  'present'
     - name: "add vlan range"  
       nxos_config:
          lines:
             - "no vlan {{ item.id }}"
          provider: "{{ provider_cisco }}"
          save: yes
       with_items: "{{  vlans_to_add }}"
       when: item.state ==  'absent'
