---
# This playbook is responsible for pushing the ansible user
# publick key file to the swtich and needs to be run as  root user
# so the login to the switch goes to the bash prompt
#
# To Run
# sudo ansible-playbook push_keys.yaml
- hosts: all
  gather_facts: no

  tasks:
     - name: copy ansible key file
       copy:
         src: "/home/ansible/.ssh/id_rsa.pub"
         dest: "/mnt/flash/ansible.pub"

      
  
     
 
