---
# This playbook will add the standard purestorage SVI config and l2 databbase on a core switch
# The group_var/all variable file has the vlans that will be added in this playbook
# see that file for more information about how to select which ones
#
# This is also part of a parent playbook called deploy_vlan but certainly can be run on its own as well
#
# This playbook also uses two template files:
#     ipv4.j2 and ipv6.j2.   This should not need to be altered  as they are used to generate the boilerplate config
#     for the playbook.  the place to add/change values will be in the group_vars/all file
#  To Run:
#  ansible-playbook core_vlan_add.yaml
- hosts: sn1-agr-e03-38,sn1-agr-e03-36
  gather_facts: no
  connection: local

  vars:
    mac: "91"
  tasks:

     # uses the ipv4.j2 template to generate L3 ipv6 for each vlan in this playbook
      - name: Deploy IPv4 Config
        eos_config:
            src: templates/ipv4_storage.j2
            provider: "{{ provider }}"
            timeout: 60
        tags: ipv4

      - name: Deploy IPv4 Config
        eos_config:
            src: templates/ipv6_storage.j2
            provider: "{{ provider }}"
            timeout: 60
        tags: ipv4

      # add l2 vlan
      - name: Deploy L2 vlan
        eos_config:
            lines: 
                - "vlan {{ item.id }}"
            provider: "{{ provider }}"
            timeout: 60
            replace: block
        with_items: "{{ vlans_to_add }}"
        when:  item.state == 'present' 
        tags: vlan

      - name: Add vlan name
        eos_config:
            lines: 
                - "name {{ item.name }}"
            provider: "{{ provider }}"
            timeout: 60
            replace: block
            parents: "vlan {{ item.id }}"
        with_items: "{{ vlans_to_add }}"
        when:  item.state == 'present' 
        tags: vlan


      # l2 vlan removal
      - name: Remove L2 vlan
        eos_config:
            lines: 
                - "no vlan {{ item.id }}"
            provider: "{{ provider }}"
            timeout: 60
        with_items: "{{ vlans_to_add }}"
        when:  item.state == 'absent' 

      - name: Add vmac
        eos_config:
            lines: 
                - " ip virtual-router mac-address 00:1a:77:01:04:{{ mac }}"
            provider: "{{ provider }}"
            timeout: 60
        when:  vlans_to_add[0].state == 'present'  



      - name:  Save Configuration
        eos_command: 
          commands: "write memory"
          provider: "{{ provider }}" 
          timeout: 60


