---
# runs through and configures interfaces on a given host
# the interfce command variable should be set with the correct
# parameters
#
# Right now you can set the following parameters
# access vlan
# switchport mode
# channel-group
# speed 40g
# mlag number
# description
# trunk native vlan
#
# If you want to add the configs you need to set action == add
# If you want to remove the configs you need to set the action == del
#
# So if you want to remove the access vlan make sure you have
# access_vlan set to a value and action set to del.  If the action is del
# then every command that is uncommented and has a value with be removed
# 
# To Run:
# ansible-playbook  config_int_commands.yaml
- hosts: sn1-rsw-b04-40,sn1-rsw-b04-41,sn1-rsw-c04-40,sn1-rsw-c04-41
  gather_facts: no
  connection: local
 
  vars:
     range: et1/1
     conf_action: add
     interface_cmds:
          # - name:  "{{ range }}"
           #  description: 'storage'
            # access_vlan: 153
            # native_vlan: 2202
           #  mode: trunk 
            # channel_group: 303
            # mlag_channel: 303
            # speed_40: Forced

           - name:  et11/1
             description: 'storage'
             channel_group: 1011
           - name:  et12/1
             description: 'storage'
             channel_group: 1012             
           - name:  et13/1
             description: 'storage'
             channel_group: 1013
           - name:  et14/1
             description: 'storage'
             channel_group: 1014


             
  tasks:
    - name: run commands
      eos_config:
         provider: "{{ provider_user_cli }}"
         src: int_config.j2
         save: true
 



